version: "3.1"

services:

  db:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test_proforma
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default

  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db
    networks:
      - default

volumes:
  persistent:

networks:
  default: